CREATE TABLE IF NOT EXISTS Block (
    id VARCHAR(36) NOT NULL DEFAULT (UUID()),
    blockerId VARCHAR(255) NOT NULL,
    blockedId VARCHAR(255) NOT NULL,
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    FOREIGN KEY (blockerId) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (blockedId) REFERENCES User(id) ON DELETE CASCADE,
    UNIQUE (blockerId, blockedId),
    INDEX (blockerId),
    INDEX (blockedId)
);