CREATE TABLE IF NOT EXISTS Follow (
    id VARCHAR(36) NOT NULL DEFAULT (UUID()),
    followerId VARCHAR(36) NOT NULL,
    followingId VARCHAR(36) NOT NULL,
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    FOREIGN KEY (followerId) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (followingId) REFERENCES User(id) ON DELETE CASCADE,
    UNIQUE (followerId, followingId),
    INDEX (followerId),
    INDEX (followingId)
);