CREATE TABLE IF NOT EXISTS User (
    id VARCHAR(36) NOT NULL DEFAULT (UUID()),
    username VARCHAR(191) NOT NULL UNIQUE,
    imageUrl TEXT NOT NULL,
    externalUserId VARCHAR(191) NOT NULL UNIQUE,
    bio TEXT NULL,
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id)
);